### PR TITLE
Styling... (open to read more)

### PR DESCRIPTION
**Pull request by La-Nique**
working on the login page--updating the colors, graphics, etc... updated the navbar to stay static on top on the pages, this is a temp feature until the navigation of the site is properly laid out also, updated the navbar styling... updated the title of the app to Persona... updated the metadata: favicon, page title... also included logo on top left of page, links back to homepage.

### CODE REVIEW

**Comment by La-Nique** [comment]
do not revert the favicon/logo and title back to geneai. re-uploading graphics because they keep getting overridden. ... navbar needs to be removed once the site layout is set, added instructions there. ... created a global styles css so the code isn't redundant. ... updated styling on the homepage ... but finished styling on the login page. ... updated layout of navbar so it's better organized for workflow. .... deleted contact.css because of redundancy ...

**Comment by La-Nique** [comment]
had to go into public folder to change metadata to replace geneai data with "persona". what's in public folder that cannot be changed? I do not understand.

**Comment by La-Nique** [comment]
cleared cache and reloaded, form is off-center, will fix next push.

**Comment by La-Nique** [comment]
++;

**Comment by La-Nique** [comment]
++;

**Comment by mike787k** [comment]
There seems to be some merge conflicts that need to be resolved before this can be merged with main. Need to fix these conflicts first

**Comment by La-Nique** [comment]
ok. I'll go ahead and merge

**Comment by mike787k** [comment]
ok looks good to me!

**Pull request merged**
